### PR TITLE
Updates: RESTful API with CRUD using PHP & MySQL

### PR DESCRIPTION
**Pull request by imakshat47**
### A complete JSON RESTful API using PHP and MySQL. We will use the SlimPHP framework along with PDO to interact with the MySQL database.

**RESTful API handles CRUD operations:**
1. Reads Data from DB using GET Request
2. Create new entries using POST Request
3. Update record using PUT Request
4. Delete record using DELETE Request

### CODE REVIEW

**Review by Kevinpaulose05 — COMMENTED** [review]
Nice topic selection. But as you are a creator you need to do lot more to what you have done presently.

1. First off stick to the folder structure as much as possible. Kindly refer to the other microbytes to get a better idea.
2.The format of readme is off. U need to provide activities that contributors can follow to understand your microbyte thru a hands-on experience.
3. Give as much documentation as possible in readme that will guide contributors to understand your microbyte. Add code snippets with main driving code hidden. After merging you can raise the incomplete part as an issue.

Ur motto is to provide a microbyte to which contributors can contribute to, not learn it by following steps blindly. U need to challenge them well by providing them only hints and asking answers via issues.

Refer to these two PRs:
https://github.com/Crio-Bytes/Miscellaneous/tree/main/Building_a_Decoupled_Voice_Assistant
https://github.com/Crio-Bytes/DSA/tree/main/BinaryTree_LevelOrderTraversal_Types

Pls don't feel intimidated. Just work on it and we r always there to help.
Cheers

**Comment by Kevinpaulose05** [comment]
> Nice topic selection. But as you are a creator you need to do something more to what you have done presently.
> 
> 1. First off stick to the folder structure as much as possible. Kindly refer to the other microbytes to get a better idea.
>    2.The format of readme is off. U need to provide activities that contributors can follow to understand your microbyte thru a hands-on experience.
> 2. Give as much documentation as possible in readme that will guide contributors to understand your microbyte. Add code snippets with main driving code hidden. After merging you can raise the incomplete part as an issue.
> 
> Ur motto is to provide a microbyte to which contributors can contribute to, not learn it by following steps blindly. U need to challenge them well by providing them only hints and asking answers via issues.
> 
> Refer to these two PRs:
> https://github.com/Crio-Bytes/Miscellaneous/tree/main/Building_a_Decoupled_Voice_Assistant
> https://github.com/Crio-Bytes/DSA/tree/main/BinaryTree_LevelOrderTraversal_Types
> 
> Pls don't feel intimidated. Just work on it and we r always there to help.
> Cheers

**NOTE:**Don't make a PR right away. Draft your microbyte first and after u have followed the guidelines make a PR.
Also avoid informal references, like localhost/FOLDER_NAME/. Explain the process illustratively by engaing the ppl in learning and googling stuff along the way

**Comment by imakshat47** [comment]
@Kevinpaulose05  Okay sure will update the above points as soon as it's merged and noted for next time.

**Comment by Kevinpaulose05** [comment]
> @Kevinpaulose05 Okay sure will update the above points as soon as it's merged and noted for next time.

This PR won't be merged. As mentioned before u have deviated from required guidelines. U will have to make necessary changes for this microbyte to get merged

**Comment by Kevinpaulose05** [comment]
You are almost there @imakshat47 . Following a proper folder structure enables us to keep track of your work. Else your work may be misjudged which we don't intend to do. U have a potential microbyte. please reolve the issues ASAP. We r awaiting your final PR.

Refer [this](https://github.com/Crio-Bytes/Networking/tree/main/traceroute) and [this](https://github.com/Crio-Bytes/Miscellaneous/tree/main/Hadoop%20Cluster) for folder structure.

Cheers

**Comment by Kevinpaulose05** [comment]
@imakshat47 Pls work on my previous comments. We are eager to merge ur PR

**Comment by Kevinpaulose05** [comment]
As we are done with #IBelieveinDoing - Hacktoberfest edition we need to close this PR as it is incomplete according to our guidelines. We are sorry to do this but we have to close this PR to avoid any further confusion on our side. We apologise for not being to guide you in the right time. Hope you participate actively in our next month's edition of #IBelieveinDoing and other events at Crio too. Till then keep contributing and all the best!

**Pull request closed without merging**
