### PR TITLE
Hotel Website 

### LINKED ISSUE #37: Hotel Website Issues
MicroByte Title: Hotel Website Issues

Domain: Web

Scope of learning for learners:
1. Solutions are not given straight away.
2. Learners can contribute by #LearnByDoingApproach

Activities:
1. Add icons from fontawesome.com.
2. Write code in HTML.
3. Styling in CSS.

### PR DESCRIPTION
**Pull request by deepak-prajapatii**
# Closes #37 

Checklist:
* [x] Added files or activities for learners.
* [x]  Give the solution hints for fixing the bugs.
* [x]  Reference material for well understand for learners.
* [x]  Comment the code in the file where the learner needs to write the code.
* [x] Added images so that learner compares their project after completing it.

### CODE REVIEW

**Comment by deepak-prajapatii** [comment]
Please review my MB.

**Comment by amoghrajesh** [comment]
Hey @deepak-prajapatii. We will review your PR as soon as possible. 
Meanwhile, can you edit your comment with the numbering of all requirements you have covered into checkboxes?
For example -

1. Added files or activities for learners.

**replaced by** 

- [x] Added files or activities for learners.

**Comment by deepak-prajapatii** [comment]
> Hey @deepak-prajapatii. We will review your PR as soon as possible. 
> Meanwhile, can you edit your comment with the numbering of all requirements you have covered into checkboxes?
> For example -
> 
> 1. Added files or activities for learners.
> 
> **replaced by** 
> 
> - [x] Added files or activities for learners. 
> 

Sure, I'll try to edit my comments as soon as possible.

**Comment by deepak-prajapatii** [comment]
> > Hey @deepak-prajapatii. We will review your PR as soon as possible.
> > Meanwhile, can you edit your comment with the numbering of all requirements you have covered into checkboxes?
> > For example -
> > 
> > 1. Added files or activities for learners.
> > 
> > **replaced by**
> > 
> > * [x]  Added files or activities for learners.
> 
> Sure, I'll try to edit my comments as soon as possible.

@amoghrajesh  How much time it takes to review  my PR?

**Comment by amoghrajesh** [comment]
Hey @deepak-prajapatii! Will get on it as soon as possible 🛩️

**Review by amoghrajesh — CHANGES_REQUESTED** [review]
Hey @deepak-prajapatii this is a good start to what you want to achieve through this MicroByte.
I would like to suggest a few changes to make it better:

1. The initial intro of HTML and CSS can be cropped out and maybe add it in the prerequisite.
2. I see you are using classes like `bg-light` which needs bootstrap too, so you probably need to make a mention of it.
3. The screenshot at the end doesn't relate to any of the code written so far, check if it is the right one.
4. You have a good file structure but which changes to make where are not very clear. (Maybe instead of designing all the pages, try to just post instructions for designing the `index.html` page that will make it much easier)
5. Although I really like your idea of TODO based filling of code by learners, you will need to provide more references as the learner can be extremely novice too.
6. My thinking is that you can make the learner design `index.html` and the rest of them can be added as learner issues. (This is my opinion, you can use what works best for you)

Again, great start. Make these small improvements and we shall re review it asap 😄

**Comment by deepak-prajapatii** [comment]
> Hey @deepak-prajapatii this is a good start to what you want to achieve through this MicroByte.
> I would like to suggest a few changes to make it better:
> 
> 1. The initial intro of HTML and CSS can be cropped out and maybe add it in the prerequisite.
> 2. I see you are using classes like `bg-light` which needs bootstrap too, so you probably need to make a mention of it.
> 3. The screenshot at the end doesn't relate to any of the code written so far, check if it is the right one.
> 4. You have a good file structure but which changes to make where are not very clear. (Maybe instead of designing all the pages, try to just post instructions for designing the `index.html` page that will make it much easier)
> 5. Although I really like your idea of TODO based filling of code by learners, you will need to provide more references as the learner can be extremely novice too.
> 6. My thinking is that you can make the learner design `index.html` and the rest of them can be added as learner issues. (This is my opinion, you can use what works best for you)
> 
> Again, great start. Make these small improvements and we shall re review it asap 😄 

I like your ideas and try to make my this contribution at its best. Thanks for your suggestion. Once I have done, I'll mention you in comments. Thank you!

**Comment by amoghrajesh** [comment]
Sure @deepak-prajapatii. 
Take your time and let's make this one a valuable one 😄

**Comment by deepak-prajapatii** [comment]
> Sure @deepak-prajapatii.
> Take your time and let's make this one a valuable one 😄

@amoghrajesh Done from my side, and there is no other framework like bootstrap in this micro bytes and I removed all other unnecessary things and provide more reference for the learner so that He/She will be able to contribute easily without any hesitation. Please review my PR.

**Review by amoghrajesh — CHANGES_REQUESTED** [review]
Hey @deepak-prajapatii!
I was going through it and it is much improved now.
I still have a few more changes to request for:

1. You have not made a mention of which files to edit as a learner (A learner might not know if he has to edit `index.html` and the CSS file, he might pick about.html)
2. Provide some references for Activity 2 and Activity 3 as right now it is completely open and the learner won't know how to do it.
3. Correct typo 'index.html' in Activity 3 and put the file names in `` so that readme file marks them as code lines and it looks visible.

Great work on improving it. Hoping to see these changes soon too 🚀

**Comment by deepak-prajapatii** [comment]
> Hey @deepak-prajapatii!
> I was going through it and it is much improved now.
> I still have a few more changes to request for:
> 
> 1. You have not made a mention of which files to edit as a learner (A learner might not know if he has to edit `index.html` and the CSS file, he might pick about.html)
> 2. Provide some references for Activity 2 and Activity 3 as right now it is completely open and the learner won't know how to do it.
> 3. Correct typo 'index.html' in Activity 3 and put the file names in `` so that readme file marks them as code lines and it looks visible.
> 
> Great work on improving it. Hoping to see these changes soon too 🚀 
> 

Sure

**Comment by deepak-prajapatii** [comment]
@amoghrajesh  Done.

**Review by amoghrajesh — APPROVED** [review]
Hi @deepak-prajapatii !
This is pretty awesome now.
It looks very nice with individual tasks having hints of their own.
I like this content. Let's see what the other reviewers feel about this 😄 
I am really impressed by you making timely changes and coming up with what it is right now 👍🏽 
Start to think of some learner issues too until this one completes review

**Comment by deepak-prajapatii** [comment]
> Hi @deepak-prajapatii !
> This is pretty awesome now.
> It looks very nice with individual tasks having hints of their own.
> I like this content. Let's see what the other reviewers feel about this 😄 
> I am really impressed by you making timely changes and coming up with what it is right now 👍🏽 
> Start to think of some learner issues too until this one completes review 

Sure and Thanks for guiding me.

**Review by Kevinpaulose05 — APPROVED** [review]
This is pretty good. I see you are getting our motto. But still, I feel there is something still lacking. pls don't take this the wrong way but I am letting you know this is for you to improve. As of now, both ur microbytes have very small code plugins needed for a learner to complete it. Try to make it more challenging and engaging. u can do this by expanding you microbytes to more advanced topics or give multiple applications of basic concepts.
Two things to be done as usual after merging:
1. open issues for learners
2. Showcase ur MB

**Comment by YourAKShaw** [comment]
@all-contributors kindly add @deepak-prajapatii for:

- [x] code
- [x] content
- [x] ideas
- [x] doc

**Comment by YourAKShaw** [comment]
@deepak-prajapatii Kindly showcase your new MicroByte in the **#microbyte-showcase** channel over at our slack workspace using [this](https://github.com/Crio-Bytes/Demo-Repo/blob/master/Maintainer%20Resources/new-microbyte-showcase-template.md) template.

**Pull request merged**
