### PR TITLE
OAuth

### PR DESCRIPTION
**Pull request by rishitha24**
I've written about what's OAuth and what is it used for.
Demonstrated Sign in with Google using OAuth

### CODE REVIEW

**Review by Kevinpaulose05 — APPROVED** [review]
Nicely done. Pls wait for another advocate to approve and then we will merge it. In the mentime if you r free try coming up with some questions for learners to learn/reply back. Also if there is any scope of contribution mention it in the readme(not compulsory) or raise an issue after merging.
cheers

**Review by sudhanshutiwari264 — APPROVED** [review]
Looks perfect ,Sounds good !🎉

**Comment by YourAKShaw** [comment]
@rishitha24 This is some quality content. Thank you for your generous work. :heart:

**Comment by Kevinpaulose05** [comment]
Next thing that you should do is showcase this PR on microbyte-showcase channel.

Kindly follow the below mentioned format for ur msg @rishitha24  -

All creators who have their PRs accepted and merged can show off their contribution in the microbyte-showcase channel. This will help the other participants by keeping them updated. Also, kindly refrain from spamming the channel with every minor contribution you may make. Please give a brief compiled overview of your contribution.

**Template (Kindly stick to this format):**
Title of your project #(repo-topic)
A brief overview of your project (not more than 3-5 lines). GITHUB LINK of byte must be provided. In the end of this briefing use #(languages), #(software), #(skills) tags.
Actively looking for contributors (both learners and creators). **Please raise an issue first and then submit your PRs to that issue only (either after or before assigning the issue to you).** Also, you can suggest how they can contribute.

**Template example:**
Concurrency #OS
Brief description. [GITHUB LINK]. #C++ #Python #Shell #Django
Actively looking for contributors. Learners can to this _ and creators can do this __. Please raise an issue first and then submit your PRs to that issue only.
#learnbydoing #microbyte-showcase

Needless to say keep contributing!!

**Comment by YourAKShaw** [comment]
@all-contributors kindly add @rishitha24  for code doc ideas content

**Pull request merged**
