### PR TITLE
added horizontal table source code to HTML Tables microbyte

### LINKED ISSUE #28: [Learners] Build a horizontal table and add it to the existing content
**MicroByte Title:** HTML Tables

**Improvement Proposal:** 

The content of [HTML Tables](https://github.com/Crio-Bytes/Web/tree/main/HTML%20Tables) microbyte can be made richer by adding a variation of the existing table (i.e. a horizontal table) with proper documentation under a separate folder. 
Here's a preview of how it's supposed to look:  

**Benefits of proposed improvements:** 

Learners will gain confidence in working with variations of HTML tables under requisite circumstances and gain confidence in building tables on their own.

### PR DESCRIPTION
**Pull request by sg23600**
Closes #28

### CODE REVIEW

**Review by amoghrajesh — CHANGES_REQUESTED** [review]
Hey @sg23600!
You've done really good work in implementing the table.
I was worried where you would place it in terms of structure and you have created a folder and placed it neatly too.
I just want to point out that you have missed out a border for your tabular structure and hence it looks like data is just floating around. 
Kindly make this one change ASAP.
Otherwise great work 😄

**Comment by sg23600** [comment]
image
@amoghrajesh Thank You for the kind words! Here is the screenshot of the table. Can you please tell me what's wrong? I can't see a missing border ...

**Comment by amoghrajesh** [comment]
It is perfect @sg23600!
Maybe I missed out on the CSS file which was linked externally.
Good work, Keep it up 😄

**Review by amoghrajesh — APPROVED** [review]

**Review by YourAKShaw — APPROVED** [review]
@sg23600 Nicely done! :rocket:

**Comment by YourAKShaw** [comment]
@all-contributors kindly add @sg23600 for code.

**Comment by sg23600** [comment]
Thank you all for merging it! Looking forwward to contribute more !!

**Pull request merged**
